# Generated by Django 4.2.7 on 2024-02-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tutors/images')),
            ],
        ),
    ]
