# Generated by Django 4.2.7 on 2024-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tutors/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
