# Generated by Django 4.2.7 on 2024-02-29 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0002_tutoraccount_delete_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tutoraccount',
            name='full_name',
        ),
        migrations.AddField(
            model_name='tutoraccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
