# Generated by Django 4.2.7 on 2024-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_hsc_gpa_alter_useraccount_hsc_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='hsc_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='hsc_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='ssc_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='ssc_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
