# Generated by Django 4.2.7 on 2024-02-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_hsc_gpa_alter_useraccount_hsc_roll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/images'),
        ),
    ]
