# Generated by Django 4.2.7 on 2024-01-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
