# Generated by Django 4.2.7 on 2024-02-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0007_rating_tutiondetails_rating_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutiondetails',
            name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
