# Generated by Django 4.2.7 on 2024-02-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0009_rating_tutiondetails_rating_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
