# Generated by Django 4.2.7 on 2024-02-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0013_remove_tutiondetails_rating_rating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
