# Generated by Django 4.2.7 on 2024-02-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0014_alter_comment_rating_delete_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='car',
            new_name='tution_detail',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=1),
        ),
    ]
