# Generated by Django 4.2.7 on 2024-02-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0019_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tution_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuitions.tutiondetails'),
        ),
    ]
